spring:
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/springboot?useSSL=false
    username: root
mybatis:
  executor-type: simple
  mapper-locations: classpath:/mybatis/mappers/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml
  type-aliases-package: com.spring.boot.mybatis.entity
  check-config-location: true
